jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      USER: ${{ secrets.DOCKER_USERNAME }}
      PASS: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Login
        run: |
          echo "User is $USER"
