name: Docker Image

on: workflow_dispatch

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app -f docker/Dockerfile .

      - name: list images
        run: docker image ls -a
