name: env variable demo
on: workflow_dispatch
env:
  APP_NAME: entrust
  APP_ENVIRONMENT: staging
  APP_VERSION: v1.4
  APP_OWNER: rizwan
  APP_REGION: ap-south-1

jobs:
  ECHO:
    runs-on: ubuntu-latest
    steps:
      - name: print env variable
        run: |
        echo "APPNAME: $APP_NAME"
        echo "APP ENVIRONMENT: $APP_ENVIRONMENT"
        echo "APP VERSION: $APP_VERSION"
        echo "APP OWNER: $APP_OWNER"
        echo "APP_REGION: $APP_REGION"






    
    

