name: pass variables

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.setname.outputs.name }}
      version: ${{ steps.setversion.outputs.version }}

    steps:
      - id: setname
        run: echo "name=rizwan" >> $GITHUB_OUTPUT

      - id: setversion
        run: echo "version=v1.4" >> $GITHUB_OUTPUT


  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - run: echo "NAME = ${{ needs.job1.outputs.name }}"


  job3:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - run: echo "VERSION = ${{ needs.job1.outputs.version }}"
