name: Hello World

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: |
          echo "Hello World"
          whoami
          uptime
  hello:
    runs-on: ubuntu-22.04
    needs: print
    steps:
      - name: run the command
        run: |
          date
          ls -ltrh
          free -g
  
